cestom_admin_homepage:
    path:     /membre/gestionMembre
    defaults: { _controller: CestomAdminBundle:GestionMembre:membre }
cestom_admin_ajouter_member:
    path:     /membre/ajouterMembre
    defaults: { _controller: CestomAdminBundle:GestionMembre:ajouterMembre }
cestom_admin_modifier_member:
    path:     /membre/modifierMembre/{idmembre}
    defaults: { _controller: CestomAdminBundle:GestionMembre:modifierMembre }
cestom_admin_modifier_formation:
    path:     /formation/modifierFormation/{idmembre}/{idformation}
    defaults: { _controller: CestomAdminBundle:GestionFormation:modifierFormationMembre }
cestom_admin_ajouter_formation:
    path:     /formation/ajouterFormation/{idmembre}
    defaults: { _controller: CestomAdminBundle:GestionFormation:ajouterFormationMembre }
cestom_admin_ajouter_ville:
    path:     /ville/gestionVille
    defaults: { _controller: CestomAdminBundle:GestionVille:ajouterVille }
cestom_admin_modifier_ville:
    path:     /ville/modifierVille/{idville}
    defaults: { _controller: CestomAdminBundle:GestionVille:modifierVille }
cestom_admin_ajouter_universite:
    path:     /universite/gestionUniversite
    defaults: { _controller: CestomAdminBundle:GestionUniversite:ajouterUniversite }
cestom_admin_modifier_universite:
    path:     /universite/modifierUniversite/{iduniversite}
    defaults: { _controller: CestomAdminBundle:GestionUniversite:modifierUniversite }
cestom_admin_ajouter_ville_membre:
    path:     /villeMembre/gestionVilleMembre/{idmembre}
    defaults: { _controller: CestomAdminBundle:GestionVilleMembre:ajouterVilleMembre }
cestom_admin_modifier_ville_membre:
    path:     /villeMembre/modifierVilleMembre/{idmembre}/{idvillemembre}
    defaults: { _controller: CestomAdminBundle:GestionVilleMembre:modifierVilleMembre }
cestom_admin_ajouter_bureau_ville:
    path:     /ville/bureau/ajouterBureau
    defaults: { _controller: CestomAdminBundle:GestionBureau:ajouterBureau }
cestom_admin_modifier_bureau_ville:
    path:     /ville/bureau/modifierBureau/{idbureau}
    defaults: { _controller: CestomAdminBundle:GestionBureau:modifierBureau }
cestom_admin_attente_bourse:
    path:     /bourse/attenteValidation
    defaults: { _controller: CestomAdminBundle:GestionBourse:listeAttenteBourse}
cestom_admin_valide_liste_bourse:
    path:     /bourse/valide
    defaults: { _controller: CestomAdminBundle:GestionBourse:listeValideBourse}
cestom_admin_rejete_liste_bourse:
    path:     /bourse/rejete
    defaults: { _controller: CestomAdminBundle:GestionBourse:listeRejeteBourse}
cestom_admin_valide_bourse:
    path:     /bourse/validation/{idbourse}
    defaults: { _controller: CestomAdminBundle:GestionBourse:validerBourse}
cestom_admin_valide_mail:
    path:     /bourse/validemail
    defaults: { _controller: CestomAdminBundle:GestionBourse:validMail}
