cestom_admin_homepage:
    path:     /membre/gestionMembre
    defaults: { _controller: CestomAdminBundle:GestionMembre:membre }
cestom_admin_ajouter_member:
    path:     /membre/ajouterMembre
    defaults: { _controller: CestomAdminBundle:AjouterMembre:ajouterMembre }
cestom_admin_modifier_member:
    path:     /membre/modifierMembre/{idmembre}
    defaults: { _controller: CestomAdminBundle:ModifierMembre:modifierMembre }
cestom_admin_modifier_formation:
    path:     /formation/modifierFormation/{idmembre}/{idformation}
    defaults: { _controller: CestomAdminBundle:ModifierFormation:modifierFormationMembre }
cestom_admin_ajouter_formation:
    path:     /formation/ajouterFormation/{idmembre}
    defaults: { _controller: CestomAdminBundle:AjouterFormation:ajouterFormationMembre }
cestom_admin_ajouter_ville:
    path:     /ville/gestionVille
    defaults: { _controller: CestomAdminBundle:AjouterVille:ajouterVille }
cestom_admin_modifier_ville:
    path:     /ville/modifierVille/{idville}
    defaults: { _controller: CestomAdminBundle:ModifierVille:modifierVille }
cestom_admin_ajouter_universite:
    path:     /universite/gestionUniversite
    defaults: { _controller: CestomAdminBundle:AjouterUniversite:ajouterUniversite }
cestom_admin_modifier_universite:
    path:     /universite/modifierUniversite/{iduniversite}
    defaults: { _controller: CestomAdminBundle:ModifierUniversite:modifierUniversite }
cestom_admin_ajouter_ville_membre:
    path:     /villeMembre/gestionVilleMembre/{idmembre}
    defaults: { _controller: CestomAdminBundle:AjouterVilleMembre:ajouterVilleMembre }
cestom_admin_modifier_ville_membre:
    path:     /villeMembre/modifierVilleMembre/{idmembre}/{idvillemembre}
    defaults: { _controller: CestomAdminBundle:ModifierVilleMembre:modifierVilleMembre }
cestom_admin_ajouter_bureau_ville:
    path:     /ville/bureau/ajouterBureau
    defaults: { _controller: CestomAdminBundle:AjouterBureauMembre:ajouterBureauMembre }
cestom_admin_modifier_bureau_ville:
    path:     /ville/bureau/modifierBureau/{idbureau}
    defaults: { _controller: CestomAdminBundle:ModifierBureauMembre:modifierBureauMembre }
