cestom_store:
    resource: "@CestomStoreBundle/Resources/config/routing.yml"
    prefix:   /

cestom_user:
    resource: "@CestomUserBundle/Resources/config/routing.yml"
    prefix:   /

cestom_admin:
    resource: "@CestomAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
