pays:
    path:     /
    defaults: { _controller: "CestomArticleBundle:Pays:index" }

pays_show:
    path:     /{id}/show
    defaults: { _controller: "CestomArticleBundle:Pays:show" }

pays_new:
    path:     /new
    defaults: { _controller: "CestomArticleBundle:Pays:new" }

pays_create:
    path:     /create
    defaults: { _controller: "CestomArticleBundle:Pays:create" }
    methods:  POST

pays_edit:
    path:     /{id}/edit
    defaults: { _controller: "CestomArticleBundle:Pays:edit" }

pays_update:
    path:     /{id}/update
    defaults: { _controller: "CestomArticleBundle:Pays:update" }
    methods:  [POST, PUT]

pays_delete:
    path:     /{id}/delete
    defaults: { _controller: "CestomArticleBundle:Pays:delete" }
    methods:  [POST, DELETE]
