<?php

namespace Proxies\__CG__\Cestom\StoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \Cestom\StoreBundle\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'libelleFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'diplomeViseFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'programmeBourse', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'dateDebutFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'dureeFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'competenceAcquise', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'idFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'iduniv', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'idmembre');
        }

        return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'libelleFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'diplomeViseFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'programmeBourse', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'dateDebutFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'dureeFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'competenceAcquise', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'idFormation', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'iduniv', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Formation' . "\0" . 'idmembre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLibelleFormation($libelleFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleFormation', array($libelleFormation));

        return parent::setLibelleFormation($libelleFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleFormation', array());

        return parent::getLibelleFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplomeViseFormation($diplomeViseFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplomeViseFormation', array($diplomeViseFormation));

        return parent::setDiplomeViseFormation($diplomeViseFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplomeViseFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplomeViseFormation', array());

        return parent::getDiplomeViseFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgrammeBourse($programmeBourse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgrammeBourse', array($programmeBourse));

        return parent::setProgrammeBourse($programmeBourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgrammeBourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgrammeBourse', array());

        return parent::getProgrammeBourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutFormation($dateDebutFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutFormation', array($dateDebutFormation));

        return parent::setDateDebutFormation($dateDebutFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutFormation', array());

        return parent::getDateDebutFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeFormation($dureeFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeFormation', array($dureeFormation));

        return parent::setDureeFormation($dureeFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeFormation', array());

        return parent::getDureeFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompetenceAcquise($competenceAcquise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompetenceAcquise', array($competenceAcquise));

        return parent::setCompetenceAcquise($competenceAcquise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetenceAcquise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetenceAcquise', array());

        return parent::getCompetenceAcquise();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFormation()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFormation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFormation', array());

        return parent::getIdFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduniv(\Cestom\StoreBundle\Entity\Universite $iduniv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduniv', array($iduniv));

        return parent::setIduniv($iduniv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduniv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduniv', array());

        return parent::getIduniv();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmembre(\Cestom\StoreBundle\Entity\Membre $idmembre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmembre', array($idmembre));

        return parent::setIdmembre($idmembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmembre', array());

        return parent::getIdmembre();
    }

}
