<?php

namespace Proxies\__CG__\Cestom\StoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fosuser extends \Cestom\StoreBundle\Entity\Fosuser implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'username', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'usernameCanonical', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'email', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'emailCanonical', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'enabled', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'salt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'password', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'lastLogin', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'locked', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'expired', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'expiresAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'confirmationToken', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'passwordRequestedAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'roles', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'credentialsExpired', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'credentialsExpireAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'username', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'usernameCanonical', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'email', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'emailCanonical', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'enabled', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'salt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'password', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'lastLogin', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'locked', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'expired', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'expiresAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'confirmationToken', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'passwordRequestedAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'roles', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'credentialsExpired', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'credentialsExpireAt', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Fosuser' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fosuser $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', array($usernameCanonical));

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', array());

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', array($emailCanonical));

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', array());

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin($lastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($lastLogin));

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($locked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($locked));

        return parent::setLocked($locked);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocked', array());

        return parent::getLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($expired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', array($expired));

        return parent::setExpired($expired);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpired', array());

        return parent::getExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt($expiresAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($expiresAt));

        return parent::setExpiresAt($expiresAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresAt', array());

        return parent::getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt($passwordRequestedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', array($passwordRequestedAt));

        return parent::setPasswordRequestedAt($passwordRequestedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', array());

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($credentialsExpired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', array($credentialsExpired));

        return parent::setCredentialsExpired($credentialsExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredentialsExpired', array());

        return parent::getCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt($credentialsExpireAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', array($credentialsExpireAt));

        return parent::setCredentialsExpireAt($credentialsExpireAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredentialsExpireAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredentialsExpireAt', array());

        return parent::getCredentialsExpireAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
