<?php

namespace Proxies\__CG__\Cestom\ArticleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \Cestom\ArticleBundle\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'titre', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introImg', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introImgFile', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'updatedAt', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'fullImg', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introduction', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'contenu', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'creation', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'debutDePublication', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'finDePublication', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'liens', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'categorie', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'pays');
        }

        return array('__isInitialized__', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'titre', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introImg', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introImgFile', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'updatedAt', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'fullImg', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'introduction', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'contenu', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'creation', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'debutDePublication', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'finDePublication', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'liens', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'categorie', '' . "\0" . 'Cestom\\ArticleBundle\\Entity\\Article' . "\0" . 'pays');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIntroImgFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntroImgFile', array($image));

        return parent::setIntroImgFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntroImgFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntroImgFile', array());

        return parent::getIntroImgFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntroduction($introduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntroduction', array($introduction));

        return parent::setIntroduction($introduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntroduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntroduction', array());

        return parent::getIntroduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', array($contenu));

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', array());

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreation($creation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreation', array($creation));

        return parent::setCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreation', array());

        return parent::getCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebutDePublication($debutDePublication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebutDePublication', array($debutDePublication));

        return parent::setDebutDePublication($debutDePublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebutDePublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebutDePublication', array());

        return parent::getDebutDePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinDePublication($finDePublication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinDePublication', array($finDePublication));

        return parent::setFinDePublication($finDePublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinDePublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinDePublication', array());

        return parent::getFinDePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntroImg($introImg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntroImg', array($introImg));

        return parent::setIntroImg($introImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntroImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntroImg', array());

        return parent::getIntroImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullImg($fullImg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullImg', array($fullImg));

        return parent::setFullImg($fullImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullImg', array());

        return parent::getFullImg();
    }

    /**
     * {@inheritDoc}
     */
    public function addLien(\Cestom\ArticleBundle\Entity\Lien $liens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLien', array($liens));

        return parent::addLien($liens);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLien(\Cestom\ArticleBundle\Entity\Lien $liens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLien', array($liens));

        return parent::removeLien($liens);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiens', array());

        return parent::getLiens();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\Cestom\ArticleBundle\Entity\Categorie $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(\Cestom\ArticleBundle\Entity\Pays $pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', array($pays));

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', array());

        return parent::getPays();
    }

}
