<?php

namespace Proxies\__CG__\Cestom\StoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membre extends \Cestom\StoreBundle\Entity\Membre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'sexe', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'nomMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'prenomMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'numeroPassportMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateExpiMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateEtabMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'promotionMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateNaissanceMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'contactUrgence', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'telephonefirst', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'telephonesecond', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'infoComplementmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'photoMimMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dernierLyceeFrequente', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'idmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'sexe', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'nomMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'prenomMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'numeroPassportMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateExpiMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateEtabMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'promotionMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dateNaissanceMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'contactUrgence', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'telephonefirst', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'telephonesecond', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'infoComplementmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'photoMimMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'dernierLyceeFrequente', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'idmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\Membre' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMembre($nomMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMembre', array($nomMembre));

        return parent::setNomMembre($nomMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMembre', array());

        return parent::getNomMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomMembre($prenomMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomMembre', array($prenomMembre));

        return parent::setPrenomMembre($prenomMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomMembre', array());

        return parent::getPrenomMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroPassportMembre($numeroPassportMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroPassportMembre', array($numeroPassportMembre));

        return parent::setNumeroPassportMembre($numeroPassportMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroPassportMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroPassportMembre', array());

        return parent::getNumeroPassportMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpiMembre($dateExpiMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpiMembre', array($dateExpiMembre));

        return parent::setDateExpiMembre($dateExpiMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpiMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpiMembre', array());

        return parent::getDateExpiMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEtabMembre($dateEtabMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEtabMembre', array($dateEtabMembre));

        return parent::setDateEtabMembre($dateEtabMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEtabMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEtabMembre', array());

        return parent::getDateEtabMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionMembre($promotionMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionMembre', array($promotionMembre));

        return parent::setPromotionMembre($promotionMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionMembre', array());

        return parent::getPromotionMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissanceMembre($dateNaissanceMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissanceMembre', array($dateNaissanceMembre));

        return parent::setDateNaissanceMembre($dateNaissanceMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissanceMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissanceMembre', array());

        return parent::getDateNaissanceMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactUrgence($contactUrgence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactUrgence', array($contactUrgence));

        return parent::setContactUrgence($contactUrgence);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactUrgence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactUrgence', array());

        return parent::getContactUrgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephonefirst($telephonefirst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephonefirst', array($telephonefirst));

        return parent::setTelephonefirst($telephonefirst);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephonefirst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephonefirst', array());

        return parent::getTelephonefirst();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephonesecond($telephonesecond)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephonesecond', array($telephonesecond));

        return parent::setTelephonesecond($telephonesecond);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephonesecond()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephonesecond', array());

        return parent::getTelephonesecond();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfoComplementmembre($infoComplementmembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfoComplementmembre', array($infoComplementmembre));

        return parent::setInfoComplementmembre($infoComplementmembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfoComplementmembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfoComplementmembre', array());

        return parent::getInfoComplementmembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoMimMembre($photoMimMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoMimMembre', array($photoMimMembre));

        return parent::setPhotoMimMembre($photoMimMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoMimMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoMimMembre', array());

        return parent::getPhotoMimMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDernierLyceeFrequente($dernierLyceeFrequente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDernierLyceeFrequente', array($dernierLyceeFrequente));

        return parent::setDernierLyceeFrequente($dernierLyceeFrequente);
    }

    /**
     * {@inheritDoc}
     */
    public function getDernierLyceeFrequente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDernierLyceeFrequente', array());

        return parent::getDernierLyceeFrequente();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmembre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmembre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmembre', array());

        return parent::getIdmembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(\Cestom\StoreBundle\Entity\Fosuser $id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
