<?php

namespace Proxies\__CG__\Cestom\StoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BureauVille extends \Cestom\StoreBundle\Entity\BureauVille implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'posteMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'idmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'idville', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'anneeScolaire');
        }

        return array('__isInitialized__', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'posteMembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'idmembre', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'idville', '' . "\0" . 'Cestom\\StoreBundle\\Entity\\BureauVille' . "\0" . 'anneeScolaire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BureauVille $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPosteMembre($posteMembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosteMembre', array($posteMembre));

        return parent::setPosteMembre($posteMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosteMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosteMembre', array());

        return parent::getPosteMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmembre(\Cestom\StoreBundle\Entity\Membre $idmembre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmembre', array($idmembre));

        return parent::setIdmembre($idmembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmembre', array());

        return parent::getIdmembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdville(\Cestom\StoreBundle\Entity\Ville $idville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdville', array($idville));

        return parent::setIdville($idville);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdville()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdville', array());

        return parent::getIdville();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeScolaire(\Cestom\StoreBundle\Entity\AnneeScolaire $anneeScolaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeScolaire', array($anneeScolaire));

        return parent::setAnneeScolaire($anneeScolaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeScolaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeScolaire', array());

        return parent::getAnneeScolaire();
    }

}
